natcom:
  redis:
    password: Redis@2021
    cluster:
      max-redirects: 2
      nodes:
        - 127.0.0.1:6377
        - 127.0.0.1:6378
        - 127.0.0.1:6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms

maria:
  datasource:
    selfcare:
      url: jdbc:mysql://10.228.102.99/selfcare
      username: SELFCARE
      password: S3lfcare$2025

oracle:
  datasource:
    my-natcom:
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=339))(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=3312))(LOAD_BALANCE=yes)(CONNECT_DATA=(SERVE=SHARED)(SERVICE_NAME= vas)))
      username: MY_NATCOM
      password: mYn@Tc0m123#$
      schema: MY_NATCOM
      driver-class-name: oracle.jdbc.OracleDriver
      configuration:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 60000
    payment:
      url: jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 333)) (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 336)) (LOAD_BALANCE = yes) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = cus) ) )
      username: MY_NATCOM
      password: mYn@Tc0m123#$
      schema: payment_haiti
      driver-class-name: oracle.jdbc.OracleDriver
      configuration:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 60000
    vas:
      url: jdbc:oracle:thin:@(description=(address_list=(address=(host=127.0.0.1)(protocol=tcp)(port=3759)) (address=(host=127.0.0.1)(protocol=tcp)(port=3761))(load_balance=yes)(failover=yes))(connect_data=(service_name=DBVASPRI)))
      username: NCFREE_SMART_CENTER
      password: nc_c@123)
      schema: ncfree_smart_center
      driver-class-name: oracle.jdbc.OracleDriver
      configuration:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 60000